#!/bin/bash
# Nima T (c) 2016
# tests pour TS

pth="../TS"
directory=`pwd`

find -name config.py

#config_file = `config.py`

cd $pth
echo "The file 'main.py' directory is: $directory"

python main.py


